// Generated by Wrangler on Sun Sep 22 2024 21:50:32 GMT+0800 (Taipei Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
	WORKER: Fetcher;
}
