/**
 * Outputs the SQL command to db/schema.sql from the JSON result of `SELECT sql FROM sqlite_master`
 */

import {readFileSync, writeFileSync} from 'fs';

const input = JSON.parse(readFileSync(0, 'utf-8'))[0].results
  .map((row: {sql: string}) => row.sql)
  .filter((sql: string) => sql !== 'null') // sqlite_autoindex_d1_migrations_1 has SQL being string "null"
  .join('\n\n');

writeFileSync('db/schema.sql', `-- Generated by npm run gen:schema\n\n${input}`);
